/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/register": {
    /** Register */
    post: operations["register_api_v1_auth_register_post"];
  };
  "/api/v1/auth/token": {
    /** Login */
    post: operations["login_api_v1_auth_token_post"];
  };
  "/api/v1/auth/refresh": {
    /**
     * Refresh Access Token
     * @description Exchange a valid refresh token for a new access token + rotated refresh token.
     */
    post: operations["refresh_access_token_api_v1_auth_refresh_post"];
  };
  "/api/v1/auth/logout": {
    /**
     * Logout
     * @description Invalidate the current refresh token (server-side logout).
     */
    post: operations["logout_api_v1_auth_logout_post"];
  };
  "/api/v1/auth/me": {
    /** Me */
    get: operations["me_api_v1_auth_me_get"];
  };
  "/api/v1/auth/verify-email": {
    /** Verify Email */
    post: operations["verify_email_api_v1_auth_verify_email_post"];
  };
  "/api/v1/auth/resend-verification": {
    /** Resend Verification */
    post: operations["resend_verification_api_v1_auth_resend_verification_post"];
  };
  "/api/v1/auth/forgot-password": {
    /** Forgot Password */
    post: operations["forgot_password_api_v1_auth_forgot_password_post"];
  };
  "/api/v1/auth/reset-password": {
    /** Reset Password */
    post: operations["reset_password_api_v1_auth_reset_password_post"];
  };
  "/api/v1/auth/users/{user_id}/role": {
    /** Update User Role */
    patch: operations["update_user_role_api_v1_auth_users__user_id__role_patch"];
  };
  "/api/v1/auth/users": {
    /** List Users */
    get: operations["list_users_api_v1_auth_users_get"];
  };
  "/api/v1/warehouses": {
    /** List Warehouses */
    get: operations["list_warehouses_api_v1_warehouses_get"];
    /** Create Warehouse */
    post: operations["create_warehouse_api_v1_warehouses_post"];
  };
  "/api/v1/warehouses/admin": {
    /** List Warehouses Admin */
    get: operations["list_warehouses_admin_api_v1_warehouses_admin_get"];
  };
  "/api/v1/warehouses/{warehouse_id}": {
    /** Get Warehouse */
    get: operations["get_warehouse_api_v1_warehouses__warehouse_id__get"];
    /** Update Warehouse */
    put: operations["update_warehouse_api_v1_warehouses__warehouse_id__put"];
    /** Delete Warehouse */
    delete: operations["delete_warehouse_api_v1_warehouses__warehouse_id__delete"];
  };
  "/api/v1/warehouses/{warehouse_id}/inventory": {
    /** Get Warehouse Inventory */
    get: operations["get_warehouse_inventory_api_v1_warehouses__warehouse_id__inventory_get"];
    /** Update Warehouse Inventory */
    put: operations["update_warehouse_inventory_api_v1_warehouses__warehouse_id__inventory_put"];
  };
  "/api/v1/safe-zones": {
    /** List Safe Zones */
    get: operations["list_safe_zones_api_v1_safe_zones_get"];
    /** Create Safe Zone */
    post: operations["create_safe_zone_api_v1_safe_zones_post"];
  };
  "/api/v1/safe-zones/admin": {
    /** List Safe Zones Admin */
    get: operations["list_safe_zones_admin_api_v1_safe_zones_admin_get"];
  };
  "/api/v1/safe-zones/{zone_id}": {
    /** Get Safe Zone */
    get: operations["get_safe_zone_api_v1_safe_zones__zone_id__get"];
    /** Update Safe Zone */
    put: operations["update_safe_zone_api_v1_safe_zones__zone_id__put"];
    /** Delete Safe Zone */
    delete: operations["delete_safe_zone_api_v1_safe_zones__zone_id__delete"];
  };
  "/api/v1/inventory/safe-zone/{zone_id}": {
    /** Stok Getir */
    get: operations["stok_getir_api_v1_inventory_safe_zone__zone_id__get"];
    /** Stok Guncelle */
    put: operations["stok_guncelle_api_v1_inventory_safe_zone__zone_id__put"];
  };
  "/api/v1/inventory/items/admin": {
    /** List Inventory Items Admin */
    get: operations["list_inventory_items_admin_api_v1_inventory_items_admin_get"];
    /** Create Inventory Item Admin */
    post: operations["create_inventory_item_admin_api_v1_inventory_items_admin_post"];
  };
  "/api/v1/inventory/items/admin/{item_id}": {
    /** Delete Inventory Item Admin */
    delete: operations["delete_inventory_item_admin_api_v1_inventory_items_admin__item_id__delete"];
    /** Update Inventory Item Admin */
    patch: operations["update_inventory_item_admin_api_v1_inventory_items_admin__item_id__patch"];
  };
  "/api/v1/inventory/warehouses/admin": {
    /** List Warehouse Inventory Admin */
    get: operations["list_warehouse_inventory_admin_api_v1_inventory_warehouses_admin_get"];
  };
  "/api/v1/inventory/warehouses/admin/{warehouse_id}/items/{item_id}": {
    /** Update Warehouse Inventory Admin */
    patch: operations["update_warehouse_inventory_admin_api_v1_inventory_warehouses_admin__warehouse_id__items__item_id__patch"];
  };
  "/api/v1/inventory/movements/admin": {
    /** List Inventory Movements Admin */
    get: operations["list_inventory_movements_admin_api_v1_inventory_movements_admin_get"];
  };
  "/api/v1/inventory/critical/admin": {
    /** List Critical Stock Admin */
    get: operations["list_critical_stock_admin_api_v1_inventory_critical_admin_get"];
  };
  "/api/v1/emergency": {
    /** Bildirimleri Getir */
    get: operations["bildirimleri_getir_api_v1_emergency_get"];
    /** Acil Bildirim Gonder */
    post: operations["acil_bildirim_gonder_api_v1_emergency_post"];
    /** Bildirimleri Temizle */
    delete: operations["bildirimleri_temizle_api_v1_emergency_delete"];
  };
  "/api/v1/emergency/admin": {
    /** Bildirimleri Getir */
    get: operations["bildirimleri_getir_api_v1_emergency_admin_get"];
  };
  "/api/v1/emergency/admin/{report_id}/status": {
    /** Update Emergency Status */
    patch: operations["update_emergency_status_api_v1_emergency_admin__report_id__status_patch"];
  };
  "/api/v1/emergency/{report_id}/image": {
    /** Upload Emergency Image */
    post: operations["upload_emergency_image_api_v1_emergency__report_id__image_post"];
  };
  "/api/v1/earthquakes": {
    /** Get Earthquakes */
    get: operations["get_earthquakes_api_v1_earthquakes_get"];
  };
  "/api/v1/earthquakes/preferences": {
    /** Get Preferences */
    get: operations["get_preferences_api_v1_earthquakes_preferences_get"];
    /** Upsert Preferences */
    put: operations["upsert_preferences_api_v1_earthquakes_preferences_put"];
  };
  "/api/v1/earthquakes/dispatch-notifications": {
    /**
     * Dispatch Notifications
     * @description Bir tarama turu: güncel depremleri kullanıcı tercihleriyle eşleştirip
     * eşleşen kullanıcılara Web Push gönderir. Harici zamanlayıcı/admin tetikler.
     */
    post: operations["dispatch_notifications_api_v1_earthquakes_dispatch_notifications_post"];
  };
  "/api/v1/profile": {
    /** Get Profile */
    get: operations["get_profile_api_v1_profile_get"];
    /** Update Profile */
    put: operations["update_profile_api_v1_profile_put"];
  };
  "/api/v1/profile/my-data": {
    /**
     * Export My Data
     * @description KVKK Madde 11 / GDPR Art. 15 — kişisel veri ihracı.
     * Kullanıcının sistemde tutulan tüm kişisel verilerini döner.
     */
    get: operations["export_my_data_api_v1_profile_my_data_get"];
  };
  "/api/v1/profile/me": {
    /**
     * Delete My Account
     * @description KVKK Madde 7 / GDPR Art. 17 — silinme hakkı.
     * Hesabı anonimleştirir: isim, e-posta hash'lenir, sağlık verisi silinir.
     * Referans bütünlüğü korunur (log kayıtları anonim olarak saklanır).
     */
    delete: operations["delete_my_account_api_v1_profile_me_delete"];
  };
  "/api/v1/spatial/nearest-depot": {
    /**
     * Nearest Depot With Required Item
     * @description Find the nearest active depot that has the requested item in stock.
     * Uses PostGIS ST_DWithin and ST_Distance over geography for meter-accurate distance.
     * Rate limited: 20 requests / 60 seconds per IP.
     */
    get: operations["nearest_depot_with_required_item_api_v1_spatial_nearest_depot_get"];
  };
  "/api/v1/spatial/nearest-safe-zone": {
    /**
     * Nearest Safe Zone
     * @description GS-031 — Capacity-aware nearest safe zone lookup.
     *
     * Returns safe zones ordered by distance. Zones with status='full' are
     * included but de-prioritised (sorted after non-full zones). Zones with
     * status='inactive' or 'closed' are excluded entirely.
     *
     * Falls back to a non-spatial distance calculation when the safe_zone
     * location column is NULL (e.g. SQLite / missing geometry migrations).
     */
    get: operations["nearest_safe_zone_api_v1_spatial_nearest_safe_zone_get"];
  };
  "/api/v1/spatial/heatmap": {
    /**
     * Incident Heatmap
     * @description GS-063 — Returns heatmap intensity points as [[lat, lon, weight], ...].
     * Incidents are weighted by status; check-ins carry uniform weight 0.5.
     * Records marked spam/dismissed are excluded.
     */
    get: operations["incident_heatmap_api_v1_spatial_heatmap_get"];
  };
  "/api/v1/volunteers": {
    /** Create Volunteer Application */
    post: operations["create_volunteer_application_api_v1_volunteers_post"];
  };
  "/api/v1/volunteers/admin": {
    /** List Volunteer Applications Admin */
    get: operations["list_volunteer_applications_admin_api_v1_volunteers_admin_get"];
  };
  "/api/v1/volunteers/admin/{volunteer_id}/status": {
    /** Update Volunteer Status */
    patch: operations["update_volunteer_status_api_v1_volunteers_admin__volunteer_id__status_patch"];
  };
  "/api/v1/shelter-offers": {
    /** Create Shelter Offer */
    post: operations["create_shelter_offer_api_v1_shelter_offers_post"];
  };
  "/api/v1/shelter-offers/admin": {
    /** List Shelter Offers Admin */
    get: operations["list_shelter_offers_admin_api_v1_shelter_offers_admin_get"];
  };
  "/api/v1/shelter-offers/admin/{offer_id}/status": {
    /** Update Shelter Offer Status */
    patch: operations["update_shelter_offer_status_api_v1_shelter_offers_admin__offer_id__status_patch"];
  };
  "/api/v1/qr/identity": {
    /** Get Qr Identity */
    get: operations["get_qr_identity_api_v1_qr_identity_get"];
  };
  "/api/v1/qr/verify": {
    /**
     * Verify Qr
     * @description Online signature verification for a QR payload.
     * Returns 200 if valid, 400 if signature mismatch, 422 if unparseable.
     * The QR scan page calls this when online; when offline it shows data without the badge.
     */
    get: operations["verify_qr_api_v1_qr_verify_get"];
  };
  "/api/v1/announcements": {
    /** List Announcements */
    get: operations["list_announcements_api_v1_announcements_get"];
    /** Create Announcement */
    post: operations["create_announcement_api_v1_announcements_post"];
  };
  "/api/v1/announcements/admin": {
    /** List Announcements Admin */
    get: operations["list_announcements_admin_api_v1_announcements_admin_get"];
  };
  "/api/v1/announcements/{announcement_id}": {
    /** Delete Announcement */
    delete: operations["delete_announcement_api_v1_announcements__announcement_id__delete"];
    /** Update Announcement */
    patch: operations["update_announcement_api_v1_announcements__announcement_id__patch"];
  };
  "/api/v1/sse/announcements": {
    /**
     * Stream Announcements
     * @description SSE endpoint — connect with EventSource('/api/v1/sse/announcements').
     * Events have type 'announcement' and carry the full announcement payload.
     */
    get: operations["stream_announcements_api_v1_sse_announcements_get"];
  };
  "/api/v1/sse/health": {
    /**
     * Sse Health
     * @description Returns the current number of connected SSE clients (for monitoring).
     */
    get: operations["sse_health_api_v1_sse_health_get"];
  };
  "/api/v1/checkin": {
    /** List Checkins */
    get: operations["list_checkins_api_v1_checkin_get"];
    /** Create Checkin */
    post: operations["create_checkin_api_v1_checkin_post"];
  };
  "/api/v1/checkin/mine": {
    /** My Checkins */
    get: operations["my_checkins_api_v1_checkin_mine_get"];
  };
  "/api/v1/routing/directions": {
    /**
     * Get Directions
     * @description Returns a GeoJSON FeatureCollection with the walking route.
     * Uses OpenRouteService when ORS_API_KEY is set; falls back to straight-line otherwise.
     */
    get: operations["get_directions_api_v1_routing_directions_get"];
  };
  "/api/v1/transfers": {
    /** List Transfers */
    get: operations["list_transfers_api_v1_transfers_get"];
    /** Create Transfer */
    post: operations["create_transfer_api_v1_transfers_post"];
  };
  "/api/v1/transfers/{transfer_id}/approve": {
    /** Approve Transfer */
    patch: operations["approve_transfer_api_v1_transfers__transfer_id__approve_patch"];
  };
  "/api/v1/transfers/{transfer_id}/reject": {
    /** Reject Transfer */
    patch: operations["reject_transfer_api_v1_transfers__transfer_id__reject_patch"];
  };
  "/api/v1/zone-needs": {
    /** List Needs */
    get: operations["list_needs_api_v1_zone_needs_get"];
    /** Report Need */
    post: operations["report_need_api_v1_zone_needs_post"];
  };
  "/api/v1/zone-needs/zone/{safe_zone_id}": {
    /** Needs For Zone */
    get: operations["needs_for_zone_api_v1_zone_needs_zone__safe_zone_id__get"];
  };
  "/api/v1/zone-needs/{need_id}/close": {
    /** Close Need */
    patch: operations["close_need_api_v1_zone_needs__need_id__close_patch"];
  };
  "/api/v1/push/vapid-public": {
    /** Vapid Public */
    get: operations["vapid_public_api_v1_push_vapid_public_get"];
  };
  "/api/v1/push/subscribe": {
    /** Subscribe */
    post: operations["subscribe_api_v1_push_subscribe_post"];
    /** Unsubscribe */
    delete: operations["unsubscribe_api_v1_push_subscribe_delete"];
  };
  "/api/v1/push/send": {
    /** Send Push */
    post: operations["send_push_api_v1_push_send_post"];
  };
  "/api/v1/reports/inventory.csv": {
    /** Export Inventory Csv */
    get: operations["export_inventory_csv_api_v1_reports_inventory_csv_get"];
  };
  "/api/v1/reports/inventory.pdf": {
    /** Export Inventory Pdf */
    get: operations["export_inventory_pdf_api_v1_reports_inventory_pdf_get"];
  };
  "/api/v1/reports/movements.csv": {
    /** Export Movements Csv */
    get: operations["export_movements_csv_api_v1_reports_movements_csv_get"];
  };
  "/api/v1/reports/checkins.csv": {
    /** Export Checkins Csv */
    get: operations["export_checkins_csv_api_v1_reports_checkins_csv_get"];
  };
  "/api/v1/admin/abuse-metrics": {
    /** Get Abuse Metrics */
    get: operations["get_abuse_metrics_api_v1_admin_abuse_metrics_get"];
  };
  "/api/v1/admin/audit-log": {
    /**
     * Get Audit Log
     * @description Paginated audit log for the activity timeline (GS-083).
     */
    get: operations["get_audit_log_api_v1_admin_audit_log_get"];
  };
  "/api/v1/volunteer-tasks": {
    /** List Open Tasks */
    get: operations["list_open_tasks_api_v1_volunteer_tasks_get"];
    /** Create Task */
    post: operations["create_task_api_v1_volunteer_tasks_post"];
  };
  "/api/v1/volunteer-tasks/admin": {
    /** List Tasks Admin */
    get: operations["list_tasks_admin_api_v1_volunteer_tasks_admin_get"];
  };
  "/api/v1/volunteer-tasks/admin/{task_id}/assign": {
    /** Assign Task */
    patch: operations["assign_task_api_v1_volunteer_tasks_admin__task_id__assign_patch"];
  };
  "/api/v1/volunteer-tasks/admin/{task_id}/status": {
    /** Update Task Status Admin */
    patch: operations["update_task_status_admin_api_v1_volunteer_tasks_admin__task_id__status_patch"];
  };
  "/api/v1/volunteer-tasks/my": {
    /** List My Tasks */
    get: operations["list_my_tasks_api_v1_volunteer_tasks_my_get"];
  };
  "/api/v1/volunteer-tasks/{task_id}/claim": {
    /** Claim Task */
    patch: operations["claim_task_api_v1_volunteer_tasks__task_id__claim_patch"];
  };
  "/api/v1/volunteer-tasks/{task_id}/complete": {
    /** Complete Task */
    patch: operations["complete_task_api_v1_volunteer_tasks__task_id__complete_patch"];
  };
  "/api/v1/volunteer-tasks/{task_id}/candidates": {
    /** Get Task Candidates */
    get: operations["get_task_candidates_api_v1_volunteer_tasks__task_id__candidates_get"];
  };
  "/api/v1/chat/messages": {
    /** Get Messages */
    get: operations["get_messages_api_v1_chat_messages_get"];
    /** Send Message */
    post: operations["send_message_api_v1_chat_messages_post"];
  };
  "/api/v1/kpi/summary": {
    /** Get Kpi Summary */
    get: operations["get_kpi_summary_api_v1_kpi_summary_get"];
  };
  "/api/v1/admin/import/warehouses": {
    /**
     * Import Warehouses
     * @description Idempotent bulk upsert of warehouses by name.
     * Returns an ImportReport showing what was (or would be) created/updated/skipped.
     */
    post: operations["import_warehouses_api_v1_admin_import_warehouses_post"];
  };
  "/api/v1/admin/import/safe-zones": {
    /**
     * Import Safe Zones
     * @description Idempotent bulk upsert of safe zones by name.
     * Returns an ImportReport showing what was (or would be) created/updated/skipped.
     */
    post: operations["import_safe_zones_api_v1_admin_import_safe_zones_post"];
  };
  "/api/v1/geofence/subscription": {
    /** Get Subscription */
    get: operations["get_subscription_api_v1_geofence_subscription_get"];
    /** Upsert Subscription */
    put: operations["upsert_subscription_api_v1_geofence_subscription_put"];
  };
  "/api/v1/geofence/dispatch": {
    /**
     * Dispatch
     * @description Bir olay konumu için yakındaki abonelere Web Push alarmı gönderir.
     */
    post: operations["dispatch_api_v1_geofence_dispatch_post"];
  };
  "/api/v1/channels": {
    /**
     * List Channels
     * @description Alan kanallarını listele. lat/lon verilirse mesafeye göre sırala ve
     * kullanıcının dairesi içindekileri 'suggested' işaretle.
     */
    get: operations["list_channels_api_v1_channels_get"];
    /** Create Channel */
    post: operations["create_channel_api_v1_channels_post"];
  };
  "/api/v1/channels/{slug}/join": {
    /** Join Channel */
    post: operations["join_channel_api_v1_channels__slug__join_post"];
  };
  "/api/v1/channels/{slug}/leave": {
    /** Leave Channel */
    post: operations["leave_channel_api_v1_channels__slug__leave_post"];
  };
  "/api/v1/channels/{slug}/messages": {
    /** Get Channel Messages */
    get: operations["get_channel_messages_api_v1_channels__slug__messages_get"];
    /** Send Channel Message */
    post: operations["send_channel_message_api_v1_channels__slug__messages_post"];
  };
  "/api/v1/channels/messages/{message_id}/report": {
    /** Report Message */
    post: operations["report_message_api_v1_channels_messages__message_id__report_post"];
  };
  "/api/v1/channels/messages/{message_id}": {
    /** Remove Message */
    delete: operations["remove_message_api_v1_channels_messages__message_id__delete"];
  };
  "/api/v1/channels/{slug}/members/{user_id}/mute": {
    /** Mute Member */
    post: operations["mute_member_api_v1_channels__slug__members__user_id__mute_post"];
  };
  "/api/v1/channels/{slug}/members/{user_id}/unmute": {
    /** Unmute Member */
    post: operations["unmute_member_api_v1_channels__slug__members__user_id__unmute_post"];
  };
  "/": {
    /** Root */
    get: operations["root__get"];
  };
  "/health": {
    /** Health */
    get: operations["health_health_get"];
  };
  "/ready": {
    /** Ready */
    get: operations["ready_ready_get"];
  };
  "/metrics": {
    /** Metrics */
    get: operations["metrics_metrics_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AnnouncementCreate */
    AnnouncementCreate: {
      /** Title */
      title: string;
      /** Content */
      content: string;
      /** Kategori */
      kategori?: string | null;
      /**
       * Priority
       * @default normal
       */
      priority?: string;
    };
    /** AnnouncementUpdate */
    AnnouncementUpdate: {
      /** Title */
      title?: string | null;
      /** Content */
      content?: string | null;
      /** Kategori */
      kategori?: string | null;
      /** Priority */
      priority?: string | null;
      /** Status */
      status?: string | null;
    };
    /** Body_login_api_v1_auth_token_post */
    Body_login_api_v1_auth_token_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /**
       * Password
       * Format: password
       */
      password: string;
      /**
       * Scope
       * @default
       */
      scope?: string;
      /** Client Id */
      client_id?: string | null;
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null;
    };
    /** Body_upload_emergency_image_api_v1_emergency__report_id__image_post */
    Body_upload_emergency_image_api_v1_emergency__report_id__image_post: {
      /** File */
      file: string;
    };
    /** ChannelCreate */
    ChannelCreate: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Center Lat */
      center_lat?: number | null;
      /** Center Lon */
      center_lon?: number | null;
      /**
       * Radius Km
       * @default 5
       */
      radius_km?: number;
    };
    /** ChannelMessageCreate */
    ChannelMessageCreate: {
      /** Body */
      body: string;
    };
    /** ChatMessageCreate */
    ChatMessageCreate: {
      /** Body */
      body: string;
      /**
       * Room
       * @default ops
       */
      room?: string;
    };
    /** CheckinCreate */
    CheckinCreate: {
      /** Name */
      name?: string | null;
      /** Lat */
      lat?: number | null;
      /** Lon */
      lon?: number | null;
      /** Note */
      note?: string | null;
      /**
       * Source
       * @default online
       */
      source?: string;
    };
    /**
     * EarthquakePreferenceUpdate
     * @description PUT gövdesi — tam temsil; verilmeyen alanlar varsayılana döner.
     */
    EarthquakePreferenceUpdate: {
      /**
       * Enabled
       * @default true
       */
      enabled?: boolean;
      /**
       * Min Magnitude
       * @default 4
       */
      min_magnitude?: number;
      /** Max Depth Km */
      max_depth_km?: number | null;
      /** Reference Lat */
      reference_lat?: number | null;
      /** Reference Lon */
      reference_lon?: number | null;
      /** Radius Km */
      radius_km?: number | null;
      /** Quiet Hours Start */
      quiet_hours_start?: number | null;
      /** Quiet Hours End */
      quiet_hours_end?: number | null;
      /** Critical Override Magnitude */
      critical_override_magnitude?: number | null;
    };
    /** EmergencyCreate */
    EmergencyCreate: {
      /** Durum */
      durum: string;
      /** Saat */
      saat: string;
      /** Harita Link */
      harita_link: string;
      /** Enlem */
      enlem: number;
      /** Boylam */
      boylam: number;
      /** Kategori */
      kategori?: string | null;
      /** Aciklama */
      aciklama?: string | null;
    };
    /** EmergencyStatusUpdate */
    EmergencyStatusUpdate: {
      /** Status */
      status: string;
    };
    /** ForgotPasswordRequest */
    ForgotPasswordRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** GeofenceDispatchPayload */
    GeofenceDispatchPayload: {
      /** Lat */
      lat: number;
      /** Lon */
      lon: number;
      /** Title */
      title: string;
      /** Body */
      body: string;
      /**
       * Url
       * @default /
       */
      url?: string;
    };
    /**
     * GeofenceSubscriptionUpdate
     * @description PUT gövdesi — tam temsil; verilmeyen alanlar varsayılana döner.
     */
    GeofenceSubscriptionUpdate: {
      /**
       * Enabled
       * @default true
       */
      enabled?: boolean;
      /** Center Lat */
      center_lat?: number | null;
      /** Center Lon */
      center_lon?: number | null;
      /**
       * Radius Km
       * @default 5
       */
      radius_km?: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InventoryUpdateItem */
    InventoryUpdateItem: {
      /** Item Id */
      item_id: number;
      /** Quantity */
      quantity: number;
    };
    /** InventoryUpdatePayload */
    InventoryUpdatePayload: {
      /** Items */
      items: components["schemas"]["InventoryUpdateItem"][];
    };
    /** ItemCreate */
    ItemCreate: {
      /** Sku */
      sku: string;
      /** Name */
      name: string;
      /**
       * Unit
       * @default unit
       */
      unit?: string;
      /** Description */
      description?: string | null;
      /** Low Stock Threshold */
      low_stock_threshold?: number | null;
      /**
       * Is Active
       * @default true
       */
      is_active?: boolean;
    };
    /** ItemUpdate */
    ItemUpdate: {
      /** Sku */
      sku?: string | null;
      /** Name */
      name?: string | null;
      /** Unit */
      unit?: string | null;
      /** Description */
      description?: string | null;
      /** Low Stock Threshold */
      low_stock_threshold?: number | null;
      /** Is Active */
      is_active?: boolean | null;
    };
    /** MessageReportCreate */
    MessageReportCreate: {
      /** Reason */
      reason?: string | null;
    };
    /** ProfileUpdate */
    ProfileUpdate: {
      /**
       * Name
       * @default
       */
      name?: string | null;
      /**
       * Blood
       * @default
       */
      blood?: string | null;
      /**
       * Chronic
       * @default
       */
      chronic?: string | null;
      /**
       * Meds
       * @default
       */
      meds?: string | null;
      /**
       * Allergy
       * @default
       */
      allergy?: string | null;
      /**
       * Phone
       * @default
       */
      phone?: string | null;
      /**
       * Disability Notes
       * @default
       */
      disability_notes?: string | null;
      /**
       * Emergency Contact Name
       * @default
       */
      emergency_contact_name?: string | null;
      /**
       * Emergency Contact Phone
       * @default
       */
      emergency_contact_phone?: string | null;
    };
    /** PushSendPayload */
    PushSendPayload: {
      /** Title */
      title: string;
      /** Body */
      body: string;
      /**
       * Url
       * @default /
       */
      url?: string | null;
      /**
       * Tag
       * @default geosafe-alert
       */
      tag?: string | null;
    };
    /** PushSubscriptionPayload */
    PushSubscriptionPayload: {
      /** Endpoint */
      endpoint: string;
      /** Keys */
      keys: {
        [key: string]: unknown;
      };
    };
    /** RefreshRequest */
    RefreshRequest: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** ResetPasswordRequest */
    ResetPasswordRequest: {
      /** Token */
      token: string;
      /** New Password */
      new_password: string;
    };
    /** RoleUpdateRequest */
    RoleUpdateRequest: {
      /** Role */
      role: string;
    };
    /** SafeZoneCreate */
    SafeZoneCreate: {
      /** Name */
      name: string;
      /** Capacity */
      capacity?: number | null;
      /**
       * Status
       * @default active
       */
      status?: string;
      /** Geometry */
      geometry: {
        [key: string]: unknown;
      };
    };
    /** SafeZoneImportRow */
    SafeZoneImportRow: {
      /** Name */
      name: string;
      /** Capacity */
      capacity?: number | null;
      /**
       * Capacity Type
       * @default persons
       */
      capacity_type?: string;
      /**
       * Status
       * @default active
       */
      status?: string;
      /** Lat */
      lat?: number | null;
      /** Lon */
      lon?: number | null;
    };
    /** ShelterOfferCreate */
    ShelterOfferCreate: {
      /** Host Name */
      host_name: string;
      /** Contact Info */
      contact_info: string;
      /** City */
      city?: string | null;
      /** District */
      district?: string | null;
      /** Neighborhood */
      neighborhood?: string | null;
      /** Address Detail */
      address_detail?: string | null;
      /** Capacity */
      capacity: number;
      /** Available From */
      available_from?: string | null;
      /** Available Until */
      available_until?: string | null;
      /** Duration Note */
      duration_note?: string | null;
      /** Household Notes */
      household_notes?: string | null;
      /** Suitability Notes */
      suitability_notes?: string | null;
    };
    /** ShelterStatusUpdate */
    ShelterStatusUpdate: {
      /** Status */
      status: string;
    };
    /** StokGuncelle */
    StokGuncelle: {
      /**
       * Water
       * @default -
       */
      water?: string | null;
      /**
       * Food
       * @default -
       */
      food?: string | null;
      /**
       * Med
       * @default -
       */
      med?: string | null;
      /**
       * Blanket
       * @default 0
       */
      blanket?: number | null;
      /**
       * Ext
       * @default 0
       */
      ext?: number | null;
    };
    /** TransferCreate */
    TransferCreate: {
      /** From Warehouse Id */
      from_warehouse_id: number;
      /** To Warehouse Id */
      to_warehouse_id: number;
      /** Item Id */
      item_id: number;
      /** Quantity */
      quantity: number;
      /** Note */
      note?: string | null;
    };
    /** UserCreate */
    UserCreate: {
      /** Name */
      name: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VolunteerCreate */
    VolunteerCreate: {
      /** Full Name */
      full_name: string;
      /** Contact Info */
      contact_info: string;
      /** District */
      district?: string | null;
      /** Neighborhood */
      neighborhood?: string | null;
      /** Skills */
      skills?: string[];
      /** Primary Role */
      primary_role?: string | null;
      /** Availability Note */
      availability_note?: string | null;
    };
    /** VolunteerStatusUpdate */
    VolunteerStatusUpdate: {
      /** Status */
      status: string;
    };
    /** VolunteerTaskAssign */
    VolunteerTaskAssign: {
      /** Assigned To Id */
      assigned_to_id?: number | null;
    };
    /** VolunteerTaskCreate */
    VolunteerTaskCreate: {
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /** Location */
      location?: string | null;
      /** Skill Required */
      skill_required?: string | null;
      /**
       * Urgency
       * @default medium
       */
      urgency?: string;
    };
    /** VolunteerTaskStatusUpdate */
    VolunteerTaskStatusUpdate: {
      /** Status */
      status: string;
    };
    /** WarehouseCreate */
    WarehouseCreate: {
      /** Name */
      name: string;
      /** Address */
      address?: string | null;
      /** Capacity */
      capacity?: number | null;
      /**
       * Status
       * @default active
       */
      status?: string;
      /** Location */
      location: {
        [key: string]: unknown;
      };
    };
    /** WarehouseImportRow */
    WarehouseImportRow: {
      /** Name */
      name: string;
      /** Address */
      address?: string | null;
      /** Lat */
      lat?: number | null;
      /** Lon */
      lon?: number | null;
      /** Capacity */
      capacity?: number | null;
      /**
       * Status
       * @default active
       */
      status?: string;
    };
    /** WarehouseInventoryAdminUpdate */
    WarehouseInventoryAdminUpdate: {
      /** Quantity */
      quantity: number;
      /**
       * Movement Type
       * @default adjustment
       */
      movement_type?: string;
      /** Note */
      note?: string | null;
    };
    /** ZoneNeedCreate */
    ZoneNeedCreate: {
      /** Safe Zone Id */
      safe_zone_id: number;
      /** Item Id */
      item_id?: number | null;
      /** Item Name Free */
      item_name_free?: string | null;
      /** Quantity Needed */
      quantity_needed: number;
      /**
       * Priority
       * @default normal
       * @enum {string}
       */
      priority?: "low" | "normal" | "high" | "critical";
      /** Note */
      note?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Register */
  register_api_v1_auth_register_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login */
  login_api_v1_auth_token_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_token_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Refresh Access Token
   * @description Exchange a valid refresh token for a new access token + rotated refresh token.
   */
  refresh_access_token_api_v1_auth_refresh_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Logout
   * @description Invalidate the current refresh token (server-side logout).
   */
  logout_api_v1_auth_logout_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Me */
  me_api_v1_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Verify Email */
  verify_email_api_v1_auth_verify_email_post: {
    parameters: {
      query: {
        token: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Resend Verification */
  resend_verification_api_v1_auth_resend_verification_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Forgot Password */
  forgot_password_api_v1_auth_forgot_password_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reset Password */
  reset_password_api_v1_auth_reset_password_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update User Role */
  update_user_role_api_v1_auth_users__user_id__role_patch: {
    parameters: {
      path: {
        user_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RoleUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Users */
  list_users_api_v1_auth_users_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** List Warehouses */
  list_warehouses_api_v1_warehouses_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Create Warehouse */
  create_warehouse_api_v1_warehouses_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["WarehouseCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Warehouses Admin */
  list_warehouses_admin_api_v1_warehouses_admin_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Get Warehouse */
  get_warehouse_api_v1_warehouses__warehouse_id__get: {
    parameters: {
      path: {
        warehouse_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Warehouse */
  update_warehouse_api_v1_warehouses__warehouse_id__put: {
    parameters: {
      path: {
        warehouse_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WarehouseCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Warehouse */
  delete_warehouse_api_v1_warehouses__warehouse_id__delete: {
    parameters: {
      path: {
        warehouse_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Warehouse Inventory */
  get_warehouse_inventory_api_v1_warehouses__warehouse_id__inventory_get: {
    parameters: {
      path: {
        warehouse_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Warehouse Inventory */
  update_warehouse_inventory_api_v1_warehouses__warehouse_id__inventory_put: {
    parameters: {
      path: {
        warehouse_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InventoryUpdatePayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Safe Zones */
  list_safe_zones_api_v1_safe_zones_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Create Safe Zone */
  create_safe_zone_api_v1_safe_zones_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SafeZoneCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Safe Zones Admin */
  list_safe_zones_admin_api_v1_safe_zones_admin_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Get Safe Zone */
  get_safe_zone_api_v1_safe_zones__zone_id__get: {
    parameters: {
      path: {
        zone_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Safe Zone */
  update_safe_zone_api_v1_safe_zones__zone_id__put: {
    parameters: {
      path: {
        zone_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SafeZoneCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Safe Zone */
  delete_safe_zone_api_v1_safe_zones__zone_id__delete: {
    parameters: {
      path: {
        zone_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Stok Getir */
  stok_getir_api_v1_inventory_safe_zone__zone_id__get: {
    parameters: {
      path: {
        zone_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Stok Guncelle */
  stok_guncelle_api_v1_inventory_safe_zone__zone_id__put: {
    parameters: {
      path: {
        zone_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StokGuncelle"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Inventory Items Admin */
  list_inventory_items_admin_api_v1_inventory_items_admin_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Create Inventory Item Admin */
  create_inventory_item_admin_api_v1_inventory_items_admin_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Inventory Item Admin */
  delete_inventory_item_admin_api_v1_inventory_items_admin__item_id__delete: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Inventory Item Admin */
  update_inventory_item_admin_api_v1_inventory_items_admin__item_id__patch: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Warehouse Inventory Admin */
  list_warehouse_inventory_admin_api_v1_inventory_warehouses_admin_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Update Warehouse Inventory Admin */
  update_warehouse_inventory_admin_api_v1_inventory_warehouses_admin__warehouse_id__items__item_id__patch: {
    parameters: {
      path: {
        warehouse_id: number;
        item_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WarehouseInventoryAdminUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Inventory Movements Admin */
  list_inventory_movements_admin_api_v1_inventory_movements_admin_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** List Critical Stock Admin */
  list_critical_stock_admin_api_v1_inventory_critical_admin_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Bildirimleri Getir */
  bildirimleri_getir_api_v1_emergency_get: {
    parameters: {
      query?: {
        /** @description Filter by status */
        status?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Acil Bildirim Gonder */
  acil_bildirim_gonder_api_v1_emergency_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmergencyCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Bildirimleri Temizle */
  bildirimleri_temizle_api_v1_emergency_delete: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Bildirimleri Getir */
  bildirimleri_getir_api_v1_emergency_admin_get: {
    parameters: {
      query?: {
        /** @description Filter by status */
        status?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Emergency Status */
  update_emergency_status_api_v1_emergency_admin__report_id__status_patch: {
    parameters: {
      path: {
        report_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmergencyStatusUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Upload Emergency Image */
  upload_emergency_image_api_v1_emergency__report_id__image_post: {
    parameters: {
      path: {
        report_id: number;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_emergency_image_api_v1_emergency__report_id__image_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Earthquakes */
  get_earthquakes_api_v1_earthquakes_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Get Preferences */
  get_preferences_api_v1_earthquakes_preferences_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Upsert Preferences */
  upsert_preferences_api_v1_earthquakes_preferences_put: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EarthquakePreferenceUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Dispatch Notifications
   * @description Bir tarama turu: güncel depremleri kullanıcı tercihleriyle eşleştirip
   * eşleşen kullanıcılara Web Push gönderir. Harici zamanlayıcı/admin tetikler.
   */
  dispatch_notifications_api_v1_earthquakes_dispatch_notifications_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Get Profile */
  get_profile_api_v1_profile_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Update Profile */
  update_profile_api_v1_profile_put: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfileUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Export My Data
   * @description KVKK Madde 11 / GDPR Art. 15 — kişisel veri ihracı.
   * Kullanıcının sistemde tutulan tüm kişisel verilerini döner.
   */
  export_my_data_api_v1_profile_my_data_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Delete My Account
   * @description KVKK Madde 7 / GDPR Art. 17 — silinme hakkı.
   * Hesabı anonimleştirir: isim, e-posta hash'lenir, sağlık verisi silinir.
   * Referans bütünlüğü korunur (log kayıtları anonim olarak saklanır).
   */
  delete_my_account_api_v1_profile_me_delete: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Nearest Depot With Required Item
   * @description Find the nearest active depot that has the requested item in stock.
   * Uses PostGIS ST_DWithin and ST_Distance over geography for meter-accurate distance.
   * Rate limited: 20 requests / 60 seconds per IP.
   */
  nearest_depot_with_required_item_api_v1_spatial_nearest_depot_get: {
    parameters: {
      query: {
        /** @description User latitude */
        lat: number;
        /** @description User longitude */
        lon: number;
        /** @description Required item name */
        item_name: string;
        /** @description Search radius in kilometers */
        radius_km?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Nearest Safe Zone
   * @description GS-031 — Capacity-aware nearest safe zone lookup.
   *
   * Returns safe zones ordered by distance. Zones with status='full' are
   * included but de-prioritised (sorted after non-full zones). Zones with
   * status='inactive' or 'closed' are excluded entirely.
   *
   * Falls back to a non-spatial distance calculation when the safe_zone
   * location column is NULL (e.g. SQLite / missing geometry migrations).
   */
  nearest_safe_zone_api_v1_spatial_nearest_safe_zone_get: {
    parameters: {
      query: {
        /** @description User latitude */
        lat: number;
        /** @description User longitude */
        lon: number;
        /** @description Max results */
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Incident Heatmap
   * @description GS-063 — Returns heatmap intensity points as [[lat, lon, weight], ...].
   * Incidents are weighted by status; check-ins carry uniform weight 0.5.
   * Records marked spam/dismissed are excluded.
   */
  incident_heatmap_api_v1_spatial_heatmap_get: {
    parameters: {
      query?: {
        /** @description incidents | checkins | both */
        source?: string;
        /** @description Include records from the last N days */
        days?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Volunteer Application */
  create_volunteer_application_api_v1_volunteers_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["VolunteerCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Volunteer Applications Admin */
  list_volunteer_applications_admin_api_v1_volunteers_admin_get: {
    parameters: {
      query?: {
        /** @description Filter by status */
        status?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Volunteer Status */
  update_volunteer_status_api_v1_volunteers_admin__volunteer_id__status_patch: {
    parameters: {
      path: {
        volunteer_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VolunteerStatusUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Shelter Offer */
  create_shelter_offer_api_v1_shelter_offers_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShelterOfferCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Shelter Offers Admin */
  list_shelter_offers_admin_api_v1_shelter_offers_admin_get: {
    parameters: {
      query?: {
        /** @description Filter by status */
        status?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Shelter Offer Status */
  update_shelter_offer_status_api_v1_shelter_offers_admin__offer_id__status_patch: {
    parameters: {
      path: {
        offer_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShelterStatusUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Qr Identity */
  get_qr_identity_api_v1_qr_identity_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Verify Qr
   * @description Online signature verification for a QR payload.
   * Returns 200 if valid, 400 if signature mismatch, 422 if unparseable.
   * The QR scan page calls this when online; when offline it shows data without the badge.
   */
  verify_qr_api_v1_qr_verify_get: {
    parameters: {
      query: {
        /** @description Base64-encoded QR payload */
        d: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Announcements */
  list_announcements_api_v1_announcements_get: {
    parameters: {
      query?: {
        /** @description Filter by category */
        kategori?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Announcement */
  create_announcement_api_v1_announcements_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnnouncementCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Announcements Admin */
  list_announcements_admin_api_v1_announcements_admin_get: {
    parameters: {
      query?: {
        /** @description Filter by status */
        status?: string | null;
        /** @description Filter by category */
        kategori?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Announcement */
  delete_announcement_api_v1_announcements__announcement_id__delete: {
    parameters: {
      path: {
        announcement_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Announcement */
  update_announcement_api_v1_announcements__announcement_id__patch: {
    parameters: {
      path: {
        announcement_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnnouncementUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Stream Announcements
   * @description SSE endpoint — connect with EventSource('/api/v1/sse/announcements').
   * Events have type 'announcement' and carry the full announcement payload.
   */
  stream_announcements_api_v1_sse_announcements_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Sse Health
   * @description Returns the current number of connected SSE clients (for monitoring).
   */
  sse_health_api_v1_sse_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** List Checkins */
  list_checkins_api_v1_checkin_get: {
    parameters: {
      query?: {
        /** @description Son kaç saatteki kayıtlar */
        hours?: number;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Checkin */
  create_checkin_api_v1_checkin_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckinCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** My Checkins */
  my_checkins_api_v1_checkin_mine_get: {
    parameters: {
      query?: {
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Directions
   * @description Returns a GeoJSON FeatureCollection with the walking route.
   * Uses OpenRouteService when ORS_API_KEY is set; falls back to straight-line otherwise.
   */
  get_directions_api_v1_routing_directions_get: {
    parameters: {
      query: {
        from_lat: number;
        from_lon: number;
        to_lat: number;
        to_lon: number;
        /** @description Routing mode (walking) */
        mode?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Transfers */
  list_transfers_api_v1_transfers_get: {
    parameters: {
      query?: {
        status?: string | null;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Transfer */
  create_transfer_api_v1_transfers_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransferCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Approve Transfer */
  approve_transfer_api_v1_transfers__transfer_id__approve_patch: {
    parameters: {
      path: {
        transfer_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reject Transfer */
  reject_transfer_api_v1_transfers__transfer_id__reject_patch: {
    parameters: {
      path: {
        transfer_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Needs */
  list_needs_api_v1_zone_needs_get: {
    parameters: {
      query?: {
        status?: string | null;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Report Need */
  report_need_api_v1_zone_needs_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ZoneNeedCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Needs For Zone */
  needs_for_zone_api_v1_zone_needs_zone__safe_zone_id__get: {
    parameters: {
      path: {
        safe_zone_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Close Need */
  close_need_api_v1_zone_needs__need_id__close_patch: {
    parameters: {
      path: {
        need_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Vapid Public */
  vapid_public_api_v1_push_vapid_public_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Subscribe */
  subscribe_api_v1_push_subscribe_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PushSubscriptionPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Unsubscribe */
  unsubscribe_api_v1_push_subscribe_delete: {
    parameters: {
      query: {
        endpoint: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Send Push */
  send_push_api_v1_push_send_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PushSendPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Export Inventory Csv */
  export_inventory_csv_api_v1_reports_inventory_csv_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Export Inventory Pdf */
  export_inventory_pdf_api_v1_reports_inventory_pdf_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Export Movements Csv */
  export_movements_csv_api_v1_reports_movements_csv_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Export Checkins Csv */
  export_checkins_csv_api_v1_reports_checkins_csv_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Get Abuse Metrics */
  get_abuse_metrics_api_v1_admin_abuse_metrics_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Get Audit Log
   * @description Paginated audit log for the activity timeline (GS-083).
   */
  get_audit_log_api_v1_admin_audit_log_get: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        resource_type?: string | null;
        action?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Open Tasks */
  list_open_tasks_api_v1_volunteer_tasks_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Create Task */
  create_task_api_v1_volunteer_tasks_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["VolunteerTaskCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Tasks Admin */
  list_tasks_admin_api_v1_volunteer_tasks_admin_get: {
    parameters: {
      query?: {
        status?: string | null;
        urgency?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Assign Task */
  assign_task_api_v1_volunteer_tasks_admin__task_id__assign_patch: {
    parameters: {
      path: {
        task_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VolunteerTaskAssign"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Task Status Admin */
  update_task_status_admin_api_v1_volunteer_tasks_admin__task_id__status_patch: {
    parameters: {
      path: {
        task_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VolunteerTaskStatusUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List My Tasks */
  list_my_tasks_api_v1_volunteer_tasks_my_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Claim Task */
  claim_task_api_v1_volunteer_tasks__task_id__claim_patch: {
    parameters: {
      path: {
        task_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Complete Task */
  complete_task_api_v1_volunteer_tasks__task_id__complete_patch: {
    parameters: {
      path: {
        task_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Task Candidates */
  get_task_candidates_api_v1_volunteer_tasks__task_id__candidates_get: {
    parameters: {
      path: {
        task_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Messages */
  get_messages_api_v1_chat_messages_get: {
    parameters: {
      query?: {
        room?: string;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Send Message */
  send_message_api_v1_chat_messages_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatMessageCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Kpi Summary */
  get_kpi_summary_api_v1_kpi_summary_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Import Warehouses
   * @description Idempotent bulk upsert of warehouses by name.
   * Returns an ImportReport showing what was (or would be) created/updated/skipped.
   */
  import_warehouses_api_v1_admin_import_warehouses_post: {
    parameters: {
      query?: {
        /** @description Preview without committing */
        dry_run?: boolean;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WarehouseImportRow"][];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Import Safe Zones
   * @description Idempotent bulk upsert of safe zones by name.
   * Returns an ImportReport showing what was (or would be) created/updated/skipped.
   */
  import_safe_zones_api_v1_admin_import_safe_zones_post: {
    parameters: {
      query?: {
        /** @description Preview without committing */
        dry_run?: boolean;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SafeZoneImportRow"][];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Subscription */
  get_subscription_api_v1_geofence_subscription_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Upsert Subscription */
  upsert_subscription_api_v1_geofence_subscription_put: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GeofenceSubscriptionUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Dispatch
   * @description Bir olay konumu için yakındaki abonelere Web Push alarmı gönderir.
   */
  dispatch_api_v1_geofence_dispatch_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GeofenceDispatchPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Channels
   * @description Alan kanallarını listele. lat/lon verilirse mesafeye göre sırala ve
   * kullanıcının dairesi içindekileri 'suggested' işaretle.
   */
  list_channels_api_v1_channels_get: {
    parameters: {
      query?: {
        lat?: number | null;
        lon?: number | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Channel */
  create_channel_api_v1_channels_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChannelCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Join Channel */
  join_channel_api_v1_channels__slug__join_post: {
    parameters: {
      path: {
        slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Leave Channel */
  leave_channel_api_v1_channels__slug__leave_post: {
    parameters: {
      path: {
        slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Channel Messages */
  get_channel_messages_api_v1_channels__slug__messages_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      path: {
        slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Send Channel Message */
  send_channel_message_api_v1_channels__slug__messages_post: {
    parameters: {
      path: {
        slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChannelMessageCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Report Message */
  report_message_api_v1_channels_messages__message_id__report_post: {
    parameters: {
      path: {
        message_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MessageReportCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Remove Message */
  remove_message_api_v1_channels_messages__message_id__delete: {
    parameters: {
      path: {
        message_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Mute Member */
  mute_member_api_v1_channels__slug__members__user_id__mute_post: {
    parameters: {
      path: {
        slug: string;
        user_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Unmute Member */
  unmute_member_api_v1_channels__slug__members__user_id__unmute_post: {
    parameters: {
      path: {
        slug: string;
        user_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Root */
  root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Health */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Ready */
  ready_ready_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Metrics */
  metrics_metrics_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "text/plain": string;
        };
      };
    };
  };
}
